# Dukung pengembangan Metasantri AI
# File ini akan menampilkan tombol "Sponsor" di halaman GitHub repo
github: [Metasantridev]
custom: ["https://saweria.co/metasantridev", "https://trakteer.id/metasantridev"]
